name: CI

on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-16.04

    env:
      ANDROID_NDK_ROOT: /opt/android-ndk-r15c

    strategy:
      matrix:
        haxe-version: [3.4.7, 4.0.5, 4.1.1]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}
    - uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Install dependencies
      run: |
        haxelib install hxcpp --quiet
        haxelib install format  --quiet
        haxelib install hxp  --quiet
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev

    - name: Install Android NDK
      run: |
        mkdir $ANDROID_NDK_ROOT
        wget -O android-ndk.zip --quiet https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
        unzip -qq android-ndk.zip -d $ANDROID_NDK_ROOT/..
        rm android-ndk.zip

    - name: Install "lime" command alias
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime setup -alias -y

    - name: Configure Lime for Android
      run: |
        lime config ANDROID_SDK $ANDROID_HOME
        haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
        haxelib run lime config JAVA_HOME $JAVA_HOME
        haxelib run lime config ANDROID_SETUP true
        haxelib run lime config

    - name: Rebuild Lime tools
      run: |
        lime rebuild tools -nocolor -verbose

    - name: Rebuild Lime binaries
      run: |
        lime rebuild linux -64 -release -verbose -nocolor
        lime rebuild linux -32 -release -verbose -nocolor
        lime rebuild hl -64 -release -verbose -nocolor
        lime rebuild android -release -verbose -nocolor

  build-macos:
    runs-on: macos-latest

    env:
      ANDROID_NDK_ROOT: /opt/android-ndk-r15c

    strategy:
      matrix:
        haxe-version: [3.4.7, 4.0.5, 4.1.1]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Install dependencies
      run: |
        haxelib install hxcpp  --quiet
        haxelib install format  --quiet
        haxelib install hxp  --quiet

    - name: Install Android NDK r15c
      run: |
        mkdir $ANDROID_NDK_ROOT
        wget -O android-ndk.zip --quiet https://dl.google.com/android/repository/android-ndk-r15c-darwin-x86_64.zip
        unzip -qq android-ndk.zip -d $ANDROID_NDK_ROOT/..
        rm android-ndk.zip

    - name: Install "lime" command alias
      run: |
        haxelib dev lime $GITHUB_WORKSPACE
        haxelib run lime setup -alias -y

    - name: Configure Lime for Android
      run: |
        lime config ANDROID_SDK $ANDROID_HOME
        haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
        haxelib run lime config JAVA_HOME $JAVA_HOME
        haxelib run lime config ANDROID_SETUP true
        haxelib run lime config

    - name: Rebuild Lime tools
      run: |
        lime rebuild tools -nocolor -verbose

    - name: Rebuild Lime binaries
      run: |
        lime rebuild mac -release -verbose -nocolor
        lime rebuild hl -release -verbose -nocolor
        lime rebuild ios -release -verbose -nocolor
        lime rebuild android -release -verbose -nocolor

  build-windows:
    runs-on: windows-latest

    env:
      ANDROID_NDK_ROOT: C:\android-ndk-r15c

    strategy:
      matrix:
        haxe-version: [3.4.7, 4.0.5, 4.1.1]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: ${{ matrix.haxe-version }}

    - name: Install dependencies
      run: |
        haxelib install hxcpp --quiet
        haxelib install format --quiet
        haxelib install hxp --quiet

    - name: Install Android NDK r15c
      run: |
        mkdir $Env:ANDROID_NDK_ROOT
        Invoke-WebRequest https://dl.google.com/android/repository/android-ndk-r15c-windows-x86_64.zip -OutFile android-ndk.zip
        Expand-Archive android-ndk.zip -DestinationPath $Env:ANDROID_NDK_ROOT/..
        rm android-ndk.zip

    - name: Install "lime" command alias
      run: |
        haxelib dev lime $Env:GITHUB_WORKSPACE
        haxelib run lime setup -alias -y

    - name: Configure Lime for Android
      run: |
        lime config ANDROID_SDK $Env:ANDROID_HOME
        haxelib run lime config ANDROID_NDK_ROOT $Env:ANDROID_NDK_ROOT
        haxelib run lime config JAVA_HOME $Env:JAVA_HOME
        haxelib run lime config ANDROID_SETUP true
        haxelib run lime config

    - name: Rebuild Lime tools
      run: |
        lime rebuild tools -nocolor -verbose

    - name: Rebuild Lime binaries
      run: |
        lime rebuild windows -32 -release -verbose -nocolor
        lime rebuild windows -64 -release -verbose -nocolor
        lime rebuild hl -32 -release -verbose -nocolor
        lime rebuild android -release -verbose -nocolor
